### ISSUE TITLE
Results list uppercase before lowercase

### ISSUE THREAD

**Issue by homebysix** [jssimporter/Spruce#1]
The report results list the scripts and packages that begin with an uppercase letter alphabetically, and then list the scripts and packages that begin with a lowercase letter alphabetically. For example:

```
########## Unused scripts:
Alpha.sh
Bravo.py
Delta.rb
Golf.sh
India.sh
Lima.py
Tango.sh
Yankee.py
charlie.sh
echo.py
hotel.py
oscar.rb
romeo.js
uniform.py
xray.sh
zulu.py
```

It would be better, I think, if the scripts were listed in alphabetical order regardless of capitalization. For example:

```
########## Unused scripts:
Alpha.sh
Bravo.py
charlie.sh
Delta.rb
echo.py
Golf.sh
hotel.py
India.sh
Lima.py
oscar.rb
romeo.js
Tango.sh
uniform.py
xray.sh
Yankee.py
zulu.py
```

**Comment by sheagcraig** [comment]
I guess it depends on how Casper users are expecting to see it. I'm used to that as the results of Bash ls sorting, and I assume it's that way because that's how the JSS spits it out.

I think sets are unordered and just happened to be sorted due to the order they're put in. I think since this tool is always going to be used with human oversight (not just full-auto blast away mode) having it be more human-parseable makes sense.

**Comment by sheagcraig** [comment]
In the next release.
