### ISSUE TITLE
Few Errors

### ISSUE THREAD

**Issue by betty02** [jssimporter/Spruce#36]
![screen shot 2019-01-10 at 14 30 24](https://user-images.githubusercontent.com/19409181/50975983-be584400-14e6-11e9-986f-0a6971fda8b3.png)

Get the above when I try and run Spruce?

**Comment by crystalllized** [comment]
I'm getting this as well, @betty02 did you ever resolve?

**Comment by betty02** [comment]
@crystalllized Nope :( Never got it sorted just ended up running a script to do what I needed instead I'm afraid!

**Comment by jwrn3** [comment]
I worked around it by reverting the version of python-jss in /Library/Python/2.7/site-packages back to v1.5 (from 2.0). I also had amend /Library/Python/2.7/site-packages/jss/tlsadapter.py so that 

ssl_version=ssl.PROTOCOL_TLSv1)

became

ssl_version=ssl.PROTOCOL_SSLv23)

We use JSSImporter in conjunction with autopkg but that uses a bundled version of python-jss so the slackening of security in the step above only affects Spruce usage.

**Comment by grahampugh** [comment]
Please try the latest version of Spruce.
